name: Terraform Apply (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to apply (main / dev / feature)"
        required: true
        default: "main"

env:
  AWS_REGION: me-central-1
  TF_IN_AUTOMATION: true

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: me-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Select Environment
        run: echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: envs/${{ env.ENV }}
        run: terraform init

      - name: Terraform Plan
        working-directory: envs/${{ env.ENV }}
        run: terraform plan

      - name: Terraform Validate
        working-directory: envs/${{ env.ENV }}
        run: terraform validate

      - name: Terraform Apply
        working-directory: envs/${{ env.ENV }}
        run: terraform apply -auto-approve
